tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
        timeout: 600    # Timeout in seconds.
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: true
